# Generated by Django 4.2.1 on 2023-05-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('measured_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
            ],
        ),
    ]
